Repository publiclab/Leaflet.DistortableImage, pull requests merged in 2019-04, with the labels that each got.

#192 issue:189 Update tests in edit folder to correct class factory syntax
  test/src/edit/DistortableImageEditSpec.js
  test/src/edit/RotateAndScaleHandleSpec.js
  test/src/edit/RotateHandleSpec.js
  test/src/edit/ScaleHandleSpec.js
Labels: ready

#191 Add class factory for L.DistortableImageOverlay
  README.md
  dist/leaflet.distortableimage.js
  examples/index.html
  examples/listeners.html
  examples/select.html
  src/DistortableImageOverlay.js
Labels: enhancement, needs-review

#196 Tests updated to use class factory syntax
  test/src/DistortableCollectionSpec.js
  test/src/DistortableImageOverlaySpec.js
Labels: ready

#187 Various toolbar updates
  dist/leaflet.distortableimage.js
  dist/leaflet.distortableimage.js.map
  src/edit/DistortableImage.Edit.js
  src/edit/DistortableImage.EditToolbar.js
Labels: bug, documentation, ready

#223 Collection class factory
  README.md
  dist/leaflet.distortableimage.js
  examples/select.html
  src/DistortableCollection.js
Labels: enhancement, ready

#217 Create pull_request_template.md
  .github/pull_request_template.md
Labels: outreach, ready

#214 Introduce chai global utilities
  test/SpecHelper.js
  test/src/DistortableCollectionSpec.js
Labels: ready, testing

#201 Toolbar positioning
  .gitignore
  README.md
  dist/leaflet.distortableimage.js
  dist/leaflet.distortableimage.js.map
  src/DistortableCollection.js
  src/DistortableImageOverlay.js
  src/edit/DistortHandle.js
  src/edit/DistortableImage.Edit.js
  src/edit/DistortableImage.EditToolbar.js
  src/edit/EditHandle.js
  src/edit/RotateAndScaleHandle.js
  src/edit/RotateHandle.js
  src/edit/ScaleHandle.js
  src/util/TrigUtil.js
  test/src/DistortableCollectionSpec.js
  test/src/DistortableImageOverlaySpec.js
Labels: bug, enhancement, in progress

#230 Update pull_request_template.md
  .github/pull_request_template.md
Labels: discussion, documentation
