Repository publiclab/Leaflet.DistortableImage, pull requests merged in 2019-05, with the labels that each got.

#237 Undefined `call` condition
  dist/leaflet.distortableimage.js
  src/edit/DistortableImage.Edit.js
Labels: bug

#245 Update L.latLng to use class factory syntax
  README.md
  examples/index.html
  examples/listeners.html
  examples/select.html
Labels: enhancement, ready

#229 Normalize keybindings
  Gruntfile.js
  README.md
  dist/leaflet.distortableimage.js
  examples/index.html
  examples/select.html
  src/DistortableCollection.js
  src/DistortableImageOverlay.js
  src/edit/DistortableImage.Edit.js
  src/edit/DistortableImage.EditToolbar.js
  src/edit/RotateScaleHandle.js
  test/SpecHelper.js
  test/karma.conf.js
  test/src/DistortableCollectionSpec.js
  test/src/edit/DistortableImageEditSpec.js
  test/src/edit/RotateScaleHandleSpec.js
Labels: bug, enhancement, needs-review

#264 Mixin deprecation
  dist/leaflet.distortableimage.js
  src/DistortableCollection.js
  src/DistortableImageOverlay.js
Labels: ready

#263 Refactored _calculateScalingFactor
  src/edit/EditHandle.js
  src/edit/RotateHandle.js
  src/edit/RotateScaleHandle.js
  src/edit/ScaleHandle.js
Labels: enhancement

#206 Add default selector
  README.md
  dist/leaflet.distortableimage.js
  examples/index.html
  examples/select.html
  package-lock.json
  src/edit/DistortableImage.Edit.js
  src/edit/tools/DistortableImage.Keymapper.js
Labels: ready

#269 Deletion bug fix
  dist/leaflet.distortableimage.js
  src/edit/DistortableImage.Edit.js
  src/edit/DistortableImage.EditToolbar.js
Labels: bug, ready

#276 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: outreach, ready

#287 Update issue templates
  .github/ISSUE_TEMPLATE/--bug-report.md
Labels: documentation, outreach

#288 Add feature template
  .github/ISSUE_TEMPLATE/--feature-request.md
Labels: documentation

#289 Create a help issue template
  .github/ISSUE_TEMPLATE/--help-with-leaflet-distortableimage.md
Labels: documentation, outreach

#294 Issue templates updated
  .github/ISSUE_TEMPLATE/--bug-report.md
  .github/ISSUE_TEMPLATE/--feature-request.md
  .github/ISSUE_TEMPLATE/--help-with-leaflet-distortableimage.md
Labels: outreach, ready
