Repository publiclab/Leaflet.DistortableImage, pull requests merged in 2019-09, with the labels that each got.

#417 #410 - Add generic method for mouse events simulation.
  test/SpecHelper.js
  test/src/DistortableCollectionSpec.js
  test/src/edit/DistortableCollectionEditSpec.js
  test/src/edit/DistortableImageEditSpec.js
Labels: ready

#425 Shift key check
  README.md
  dist/leaflet.distortableimage.js
  examples/index.html
  package-lock.json
  package.json
  src/edit/DistortableCollection.Edit.js
  src/edit/DistortableImage.Edit.js
  src/edit/LockHandle.js
  src/mapmixins/DoubleClickLabels.js
  src/mapmixins/MapMixins.js
  src/util/DomUtil.js
Labels: bug, ready

#424 Pixelorigin
  README.md
  debug/pixelorigin.html
  dist/leaflet.distortableimage.js
  package-lock.json
  package.json
  src/DistortableImageOverlay.js
  src/edit/DistortableImage.Edit.js
  src/edit/RotateHandle.js
  src/edit/RotateScaleHandle.js
  src/edit/ScaleHandle.js
Labels: bug, ready

#393 Hotkeys and major file restructuring
  .eslintignore
  .eslintrc.js
  Gruntfile.js
  README.md
  dist/leaflet.distortableimage.css
  dist/leaflet.distortableimage.js
  examples/select.html
  package-lock.json
  package.json
  src/DistortableCollection.js
  src/DistortableImageOverlay.js
  src/components/DistortableImage.Keymapper.js
  src/edit/DistortableCollection.Edit.js
  src/edit/DistortableImage.Edit.js
  src/edit/actions/BorderAction.js
  src/edit/actions/DeleteAction.js
  src/edit/actions/DistortAction.js
  src/edit/actions/EditAction.js
  src/edit/actions/ExportAction.js
  src/edit/actions/FreeRotateAction.js
  src/edit/actions/GeolocateAction.js
  src/edit/actions/LockAction.js
  src/edit/actions/OpacityAction.js
  src/edit/actions/RevertAction.js
  src/edit/actions/RotateAction.js
  src/edit/actions/ScaleAction.js
  src/edit/actions/StackAction.js
  src/edit/handles/DistortHandle.js
  src/edit/handles/EditHandle.js
  src/edit/handles/FreeRotateHandle.js
  src/edit/handles/LockHandle.js
  src/edit/handles/RotateHandle.js
  src/edit/handles/ScaleHandle.js
  src/edit/toolbars/DistortableImage.ControlBar.js
  src/edit/toolbars/DistortableImage.PopupBar.js
  src/edit/tools/DistortableImage.ControlBar.js
  src/edit/tools/DistortableImage.PopupBar.js
  src/iconsets/ToolbarIconSet.js
  src/mapmixins/BoxSelector.js
  test/SpecHelper.js
  test/karma.conf.js
  test/src/DistortableCollectionSpec.js
  test/src/edit/DistortableCollectionEditSpec.js
  test/src/edit/DistortableImageEditSpec.js
Labels: API, bug, needs-review

#431 Hotfix
  README.md
  dist/leaflet.distortableimage.css
  dist/leaflet.distortableimage.js
  examples/select.html
  package-lock.json
  package.json
  src/DistortableCollection.js
  src/DistortableImageOverlay.js
  src/edit/DistortableCollection.Edit.js
  src/edit/DistortableImage.Edit.js
  src/edit/actions/DeleteAction.js
  src/edit/actions/ExportAction.js
  src/edit/actions/LockAction.js
  src/mapmixins/BoxCollector.js
  src/mapmixins/DoubleClickLabels.js
  test/src/DistortableCollectionSpec.js
  test/src/edit/DistortableCollectionEditSpec.js
  test/src/edit/DistortableImageEditSpec.js
Labels: API, bug, ready

#434 Fix `setCornersFromPoints` and expose to API
  README.md
  debug/pixelorigin.html
  dist/leaflet.distortableimage.js
  package-lock.json
  package.json
  src/DistortableCollection.js
  src/DistortableImageOverlay.js
  src/edit/DistortableImage.Edit.js
  src/edit/actions/BorderAction.js
  src/edit/actions/DeleteAction.js
  src/edit/actions/OpacityAction.js
Labels: API, bug, documentation, ready

#435 Eslint
  package.json
Labels: dependencies

#433 Expose `Select` and `deselect` to API
  README.md
  dist/leaflet.distortableimage.js
  package-lock.json
  package.json
  src/DistortableCollection.js
  src/DistortableImageOverlay.js
  src/edit/DistortableCollection.Edit.js
  src/edit/DistortableImage.Edit.js
  src/edit/handles/ScaleHandle.js
  test/src/DistortableCollectionSpec.js
  test/src/DistortableImageOverlaySpec.js
  test/src/edit/DistortableCollectionEditSpec.js
  test/src/edit/DistortableImageEditSpec.js
Labels: API, documentation, ready

#438 Tapevents
  Gruntfile.js
  README.md
  debug/pixelorigin.html
  dist/leaflet.distortableimage.js
  examples/index.html
  examples/listeners.html
  examples/select.html
  package-lock.json
  package.json
  src/DistortableImageOverlay.js
  src/edit/DistortableCollection.Edit.js
  src/edit/actions/EditAction.js
  src/edit/handles/EditHandle.js
  src/mapmixins/BoxCollector.js
  src/mapmixins/DoubleClickLabels.js
  src/mapmixins/DoubleClickZoom.js
  src/mapmixins/MapMixins.js
  test/karma.conf.js
  test/src/DistortableImageOverlaySpec.js
  test/src/edit/DistortableCollectionEditSpec.js
  test/src/edit/DistortableImageEditSpec.js
Labels: bug, ready

#371 Add DRAG mode, this let you move object with the handlers and nothing else (ok)
  assets/icons/svg-min/drag.svg
  assets/icons/svg-min/transform.svg
  assets/icons/svg/drag.svg
  assets/icons/svg/transform.svg
  assets/icons/symbol/sprite.symbol.html
  assets/icons/symbol/sprite.symbol.svg
  dist/leaflet.distortableimage.css
  dist/leaflet.distortableimage.js
  package-lock.json
  package.json
  src/DistortableImageOverlay.js
  src/components/DistortableImage.Keymapper.js
  src/edit/DistortableImage.Edit.js
  src/edit/actions/DragAction.js
  src/edit/handles/DragHandle.js
  src/edit/handles/FreeRotateHandle.js
  src/edit/toolbars/DistortableImage.PopupBar.js
  src/iconsets/ToolbarIconSet.js
  src/mapmixins/BoxCollector.js
Labels: needs-review
