Repository publiclab/Leaflet.DistortableImage, pull requests merged in 2019-07, with the labels that each got.

#314 Multi export
  Gruntfile.js
  README.md
  assets/icons/symbol/sprite.symbol.html
  bower.json
  dist/leaflet.distortableimage.js
  dist/leaflet.distortableimage.js.map
  examples/index.html
  examples/listeners.html
  examples/mirror.png
  examples/select.html
  package-lock.json
  package.json
  src/DistortableCollection.js
  src/DistortableImageOverlay.js
  src/edit/BoxSelectHandle.js
  src/edit/BoxSelector.js
  src/edit/DistortHandle.js
  src/edit/DistortableImage.Edit.js
  src/edit/DistortableImage.EditToolbar.js
  src/edit/DistortableImage.Keymapper.js
  src/edit/tools/DistortableImage.ControlBar.js
  src/edit/tools/DistortableImage.PopupBar.js
  src/edit/tools/EditAction.js
  src/util/DomUtil.js
  src/util/ImageUtil.js
  test/SpecHelper.js
  test/karma.conf.js
  test/src/DistortableCollectionSpec.js
  test/src/edit/DistortableImageEditSpec.js
Labels: needs-review

#324 Toggle locks
  README.md
  dist/leaflet.distortableimage.js
  examples/select.html
  package.json
  src/DistortableCollection.js
  src/edit/DistortableImage.Edit.js
  src/edit/tools/DistortableImage.ControlBar.js
  test/src/DistortableCollectionSpec.js
Labels: needs-review

#303 Long press unlock
  README.md
  dist/leaflet.distortableimage.js
  src/DistortableCollection.js
Labels: ready

#334 Box selector selection direction fix
  dist/leaflet.distortableimage.js
  src/DistortableCollection.js
  src/edit/BoxSelector.js
  src/edit/DistortableImage.Edit.js
  test/src/DistortableCollectionSpec.js
Labels: needs-review

#337 Npm badge
  README.md
Labels: documentation

#329 Initial selected
  README.md
  dist/leaflet.distortableimage.js
  package-lock.json
  src/DistortableCollection.js
  src/edit/DistortableImage.Edit.js
Labels: ready

#346 Restore to revert
  README.md
  dist/leaflet.distortableimage.js
  src/edit/DistortableImage.Edit.js
  src/edit/tools/DistortableImage.PopupBar.js
Labels: ready

#344 Box select debug
  debug/pixelorigin.html
  dist/leaflet.distortableimage.js
  package-lock.json
  package.json
  src/DistortableCollection.js
  src/edit/BoxSelector.js
  src/edit/DistortHandle.js
  src/util/Map._newLayerPointToLatLng.js
  src/util/MapMixins.js
Labels: ready

#347 Fix Firefox Zoom animation
  dist/leaflet.distortableimage.js
  src/DistortableImageOverlay.js
Labels: ready

#359 Contributors
  README.md
Labels: documentation, ready

#353 Svg stack
  Gruntfile.js
  assets/icons/svg-min/border_clear.svg
  assets/icons/svg-min/border_outer.svg
  assets/icons/svg-min/crop_rotate.svg
  assets/icons/svg-min/delete_forever.svg
  assets/icons/svg-min/explore.svg
  assets/icons/svg-min/flip_to_back.svg
  assets/icons/svg-min/flip_to_front.svg
  assets/icons/svg-min/get_app.svg
  assets/icons/svg-min/lock.svg
  assets/icons/svg-min/opacity-empty.svg
  assets/icons/svg-min/opacity.svg
  assets/icons/svg-min/opacity_empty.svg
  assets/icons/svg-min/restore.svg
  assets/icons/svg-min/transform.svg
  assets/icons/svg-min/unlock.svg
  assets/icons/svg/border_clear.svg
  assets/icons/svg/border_outer.svg
  assets/icons/svg/crop_rotate.svg
  assets/icons/svg/delete_forever.svg
  assets/icons/svg/explore.svg
  assets/icons/svg/flip_to_back.svg
  assets/icons/svg/flip_to_front.svg
  assets/icons/svg/get_app.svg
  assets/icons/svg/lock.svg
  assets/icons/svg/opacity-empty.svg
  assets/icons/svg/opacity.svg
  assets/icons/svg/opacity_empty.svg
  assets/icons/svg/restore.svg
  assets/icons/svg/transform.svg
  assets/icons/svg/unlock.svg
  assets/icons/symbol/sprite.symbol.html
  assets/icons/symbol/sprite.symbol.svg
  dist/leaflet.distortableimage.css
  dist/leaflet.distortableimage.js
  examples/index.html
  examples/listeners.html
  examples/select.html
  package-lock.json
  package.json
  src/edit/DistortableImage.Edit.js
  src/edit/DistortableImage.Keymapper.js
  src/edit/tools/DistortableImage.ControlBar.js
  src/edit/tools/DistortableImage.PopupBar.js
  src/edit/tools/EditAction.js
  src/edit/tools/IconSet.js
  test/karma.conf.js
Labels: ready

#241 Remove bower.json from root folder and bower components from .gitignore
  .gitignore
  bower.json
Labels: dependencies, ready

#366 Add contributors welcome badge
  README.md
Labels: documentation, enhancement

#243 Keymapper phase 2 enhancements
  Gruntfile.js
  README.md
  assets/icons/svg-min/crop_rotate.svg
  assets/icons/svg-min/explore.svg
  assets/icons/svg-min/flip_to_back.svg
  assets/icons/svg-min/flip_to_front.svg
  assets/icons/svg-min/keyboard_open.svg
  assets/icons/svg-min/lock.svg
  assets/icons/svg-min/opacity.svg
  assets/icons/svg-min/opacity_empty.svg
  assets/icons/svg-min/restore.svg
  assets/icons/svg-min/unlock.svg
  assets/icons/svg/keyboard_open.svg
  assets/icons/symbol/sprite.symbol.html
  assets/icons/symbol/sprite.symbol.svg
  dist/leaflet.distortableimage.css
  dist/leaflet.distortableimage.js
  examples/index.html
  examples/listeners.html
  examples/select.html
  package-lock.json
  package.json
  src/components/DistortableImage.Keymapper.js
  src/edit/BoxSelector.js
  src/edit/DistortableImage.Edit.js
  src/edit/DistortableImage.Keymapper.js
  src/edit/EditHandle.js
  src/edit/tools/DistortableImage.PopupBar.js
  src/edit/tools/EditAction.js
  src/iconsets/IconSet.js
  src/iconsets/KeymapperIconSet.js
  src/iconsets/ToolbarIconSet.js
  src/util/IconUtil.js
  test/karma.conf.js
  test/src/edit/DistortableImageEditSpec.js
Labels: bug, ready
