Repository publiclab/Leaflet.DistortableImage, pull requests merged in 2020-01, with the labels that each got.

#482 Add lock mode tooltips
  .eslintrc.js
  dist/leaflet.distortableimage.js
  package-lock.json
  package.json
  src/edit/DistortableImage.Edit.js
  src/edit/handles/DistortHandle.js
  src/edit/handles/EditHandle.js
  src/edit/handles/LockHandle.js
  src/edit/handles/RotateHandle.js
  src/edit/handles/ScaleHandle.js
  src/util/MatrixUtil.js
  test/src/edit/EditHandleSpec.js
Labels: in progress

#485 [WIP] customizable export UI for DistortableCollection
  dist/leaflet.distortableimage.js
  examples/export.html
  package.json
  src/edit/DistortableCollection.Edit.js
  src/edit/actions/ExportAction.js
Labels: needs-review

#519 Feature/cancel export rebased & bug fixes to customizable export UI
  .eslintrc.js
  assets/icons/svg-min/cancel.svg
  assets/icons/svg/cancel.svg
  assets/icons/symbol/sprite.symbol.html
  assets/icons/symbol/sprite.symbol.svg
  dist/leaflet.distortableimage.css
  dist/leaflet.distortableimage.js
  examples/export.html
  package-lock.json
  package.json
  src/DistortableCollection.js
  src/edit/DistortableCollection.Edit.js
  src/edit/actions/ExportAction.js
  src/iconsets/ToolbarIconSet.js
  src/util/Utils.js
Labels: high-priority, needs-review
